CREATE TABLE IF NOT EXISTS students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    record_book_number VARCHAR(20) UNIQUE NOT NULL,
    subgroup INT NOT NULL CHECK (subgroup BETWEEN 1 AND 3),
    phone VARCHAR(20),
    email VARCHAR(100),
    birth_date DATE,
    password_hash VARCHAR(255),
    telegram_id BIGINT UNIQUE,
    registered_at TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE NOT NULL
);
ALTER TABLE students ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(500);
ALTER TABLE students ADD COLUMN IF NOT EXISTS theme_color VARCHAR(20) DEFAULT 'peach' NOT NULL;
CREATE TABLE IF NOT EXISTS schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_type VARCHAR(20) NOT NULL CHECK (week_type IN ('числитель', 'знаменатель')),
    day_of_week VARCHAR(10) NOT NULL,
    subgroup INT NOT NULL CHECK (subgroup BETWEEN 1 AND 3),
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    discipline VARCHAR(255) NOT NULL,
    CONSTRAINT uq_schedule_week_day_subgroup UNIQUE (week_type, day_of_week, subgroup)
);
CREATE TABLE IF NOT EXISTS attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    time TIME NOT NULL,
    week_type VARCHAR(20) NOT NULL CHECK (week_type IN ('числитель', 'знаменатель')),
    subgroup INT NOT NULL CHECK (subgroup BETWEEN 1 AND 3),
    CONSTRAINT uq_attendance_student_date UNIQUE (student_id, date)
);
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS marked_by VARCHAR(255);
CREATE TABLE IF NOT EXISTS posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT,
    file_url VARCHAR(500),
    file_name VARCHAR(255),
    for_subgroup INT CHECK (for_subgroup IS NULL OR for_subgroup BETWEEN 1 AND 3),
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS attendance_windows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subgroup INT NOT NULL CHECK (subgroup BETWEEN 1 AND 3),
    week_type VARCHAR(20) NOT NULL CHECK (week_type IN ('числитель', 'знаменатель')),
    day_of_week VARCHAR(10) NOT NULL,
    schedule_id BIGINT REFERENCES schedule(id) ON DELETE SET NULL,
    opened_at TIMESTAMP NOT NULL,
    closes_at TIMESTAMP NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    opened_by VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS app_settings (
    id BIGINT PRIMARY KEY,
    week_anchor_date DATE,
    week_anchor_type VARCHAR(20)
);
CREATE TABLE IF NOT EXISTS excuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    date_from DATE NOT NULL,
    date_to DATE NOT NULL,
    reason_type VARCHAR(30) NOT NULL,
    comment VARCHAR(1000),
    file_url VARCHAR(500),
    file_name VARCHAR(255),
    created_at TIMESTAMP NOT NULL
);
